### ISSUE TITLE
Problem using/running the lib with next.js

### ISSUE THREAD

**Issue by lishine** [react-financial/react-financial-charts#582]
```
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/a/dev/trade/node_modules/@react-financial-charts/annotations/l
ib/Annotate' imported from /home/a/dev/trade/node_modules/@react-financial-charts/annotations/lib/index.js
    at finalizeResolution (internal/modules/esm/resolve.js:271:11)
    at moduleResolve (internal/modules/esm/resolve.js:694:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

Just trying to use for the first time.
I am just using the StockChart.tsx as it is. I copied the data folder, and installed the npm packages.

BTW in StockChart.tsx I get these ts errors in the editor (which does not interfer with running)

```
Exported variable 'StockChartExported' has or is using name 'WithOHLCState' from external module "/home/a/dev/trade/www/src/features/data/withOHLCData" but cannot be named.ts(4023)
```

Tried to adapt tsconig as close to the stories tsconfig, but it didn't help.

Can I see somewhere (like in codesandbox or with CRA) that it is working.

I see the Annotations exist in the node_modules ...

**Comment by markmcdowell** [comment]
It's worth searching for issues/discussions before raising a new one. This has been answered many times.

**Comment by markmcdowell** [comment]
It's worth searching for issues/discussions before raising a new one. This has been answered many times.

**Comment by pyrotechnick** [comment]
I'm also experiencing this issue.

FWIW I have searched the issues/discussions for terms such as "annotation" and "nextjs" and it appears as though this particular issue has not been worked through or discussed.
