### ISSUE TITLE
was not found in 'react-financial-charts' (possible exports: defaultScaleProvider)

### ISSUE THREAD

**Issue by mmavka** [react-financial/react-financial-charts#616]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
The project compiles, but errors occur

#### Please tell us about your environment

- Version: 1.3.2
- Browser: [all]
- Using TypeScript: yes (I created the application with npx create-react-app. --template typescript)

#### Other information

Error ecemple:

> 
> ERROR in ./src/StockChart.tsx 302:57-65
> 
> export 'withSize' (imported as 'withSize') was not found in 'react-financial-charts' (possible exports: defaultScaleProvider)
> 
> 
> ERROR in ./src/StockChart.tsx 306:3-18
> 
> export 'withDeviceRatio' (imported as 'withDeviceRatio') was not found in 'react-financial-charts' (possible exports: defaultScaleProvider)
> 
> 
> ERROR in ../../node_modules/@react-financial-charts/annotations/lib/index.js 1:0-27
> 
> Module not found: Error: Can't resolve './Annotate' in 'C:\Users\mmavka\projects\react\react-monorepo-template\node_modules\@react-financial-charts\annotations\lib'
> Did you mean 'Annotate.js'?
> BREAKING CHANGE: The request './Annotate' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
> 
> 
> ERROR in ../../node_modules/@react-financial-charts/annotations/lib/index.js 2:0-32
> 
> Module not found: Error: Can't resolve './BarAnnotation' in 'C:\Users\mmavka\projects\react\react-monorepo-template\node_modules\@react-financial-charts\annotations\lib'
> Did you mean 'BarAnnotation.js'?
> BREAKING CHANGE: The request './BarAnnotation' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
> `

**Comment by markmcdowell** [comment]
Duplicate #606

**Comment by mmavka** [comment]
I create not NEXT app

**Comment by matteo-maggiolo** [comment]
have the same bug, not using next as well..

**Comment by briang7** [comment]
same
