### ISSUE TITLE
@react-financial-charts/annotations missing

### ISSUE THREAD

**Issue by NoCluePS** [react-financial/react-financial-charts#633]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
Throws an error, that explains that there's some module missing called  @react-financial-charts/annotations, tried installing it and running it again, didn't help in my case

![Screenshot 2022-04-04 at 18 44 05](https://user-images.githubusercontent.com/93134247/161581941-91a98a41-9ae8-4121-9a49-9a9533558205.png)

#### What is the expected behavior
There should be a chart with dummy data showing

#### Please tell us about your environment
MacOS Monterey,  M1 chip, 16gb ram, vsCode, React, NextJS

- Version: 1.1.0
- Browser: [all | Chrome XX | Firefox XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]

**Comment by rnnyrk** [comment]
Same issue for me. Working fine, but after refreshing the page this error appears

**Comment by markmcdowell** [comment]
This is likely something to do with the module flag, please try with latest version.
