### ISSUE TITLE
Conflict with react^18

### ISSUE THREAD

**Issue by SamanAbasi** [react-financial/react-financial-charts#646]
Conflict with react^18

**Comment by sjclark76** [comment]
This would be great to get this working with React 18 as we need to upgrade our site

**Comment by alex-klepa** [comment]
+1

**Comment by ferrants** [comment]
Heads up, this fork and branch is for react 18, not sure if it's ready, but using it could help validate that it's ready for a PR
https://github.com/adamhwang/react-financial-charts/tree/react18

**Comment by dulabs** [comment]
@ferrants can you PR this patch?

**Comment by ferrants** [comment]
@dulabs here you go
https://github.com/react-financial/react-financial-charts/pull/668

**Comment by metamaker** [comment]
Bump ^

Can we merge the PR?

**Comment by GOATsann** [comment]
Bump ^

Can we merge the PR?

**Comment by markmcdowell** [comment]
there's a comment on the PR that's waiting to be resolved before being merged.

**Comment by markmcdowell** [comment]
Resolved in [v2.0.0](https://github.com/react-financial/react-financial-charts/releases/tag/v2.0.0)
