### ISSUE TITLE
Please publish 1.3.3 to support React 18 Component props type

### ISSUE THREAD

**Issue by chang-ke** [react-financial/react-financial-charts#653]
#### I'm submitting a...

- [ ] bug
- [x] feature
- [ ] chore

#### What is the current behavior
V1.3.2 typescript decalre not support React 18
#### What is the expected behavior
Typescript decalre support React 18
#### Please tell us about your environment

- Version: 1.3.2
- Browser: [all | Chrome XX | Firefox XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]

**Comment by metamaker** [comment]
Bump ^

**Comment by markmcdowell** [comment]
Resolved in [v2.0.0](https://github.com/react-financial/react-financial-charts/releases/tag/v2.0.0)
