### ISSUE TITLE
please consider to remove react

### ISSUE THREAD

**Issue by ts-00** [react-financial/react-financial-charts#665]
#### I'm submitting a...

- [ ] bug
- [x] feature
- [ ] chore

#### What is the current behavior

The lib depends on react.

#### What is the expected behavior

The lib should be also usable in non react environments. We already have e.g. "WebComponents" which does not depend on react to build components.

#### Please tell us about your environment

A non react environment.

#### Other information

Maybe you can evaluate to abandon react from `financial-charts` so it's usable without the need to include react.

**Comment by markmcdowell** [comment]
Unlikely to do this.
